backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/assets
public_folder: public
local_backend: true
collections:
  - name: "projects"
    label: "Projects"
    label_singular: 'Project'
    folder: "content/projects"
    create: true
    path: "{{slug}}/{{slug}}.md"
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "URL Slug", name: "slug", widget: "string"}
      - { label: "Cover Image", name: "cover", widget: "image"}
      - { label: "Project Date", name: "date", widget: "datetime", format: "yyyy-MM-dd" }
      - label: Tags
        name: tags
        widget: list
        fields:
          - {label: Tag, name: tag, widget: string}
      - { label: "Authors", name: "authors", widget: "list", required: false } 
      - { label: "Subsite URL", name: "subsite", widget: "string", required: false}
      - { label: "Description", name: "description", widget: "markdown"}
      - { label: "Aim", name: "aim", widget: "markdown"}
      - { label: "Body", name: "body", widget: "markdown", required: false}

  - name: "blog"
    label: "Blog Posts"
    label_singular: 'Blog Post'
    folder: "content/blog"
    create: true
    path: "{{slug}}/{{slug}}.md"
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "URL Slug", name: "slug", widget: "string"}
      - { label: "Cover Image", name: "cover", widget: "image"}
      - { label: "Project Date", name: "date", widget: "datetime", format: "yyyy-MM-dd" }
      - label: Tags
        name: tags
        widget: list
        fields:
          - {label: Tag, name: tag, widget: string}
      - { label: "Authors", name: "authors", widget: "list", required: false } 
      - { label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    label_singular: 'Page'
    files:
      - label: "Home Page"
        name: "index"
        file: "content/pages/index.yml"
        fields:
          - { label: About Heading, name: about-heading, widget: string}
          - { label: About Text, name: about-text, widget: markdown}
          - { label: About Image, name: about-image, widget: image}
          
      - label: "About Page"
        name: "about"
        file: "content/pages/about.yml"
        fields:
          - label: Sections
            name: sections
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: Text, name: text, widget: markdown}